@ARAS.Auth.Api_HostAddress = https://localhost:3002

GET {{ARAS.Auth.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ARAS.Auth.Api_HostAddress}}/api/auth/aad/login

###

GET {{ARAS.Auth.Api_HostAddress}}/api/ops/accounts

###

GET {{ARAS.Auth.Api_HostAddress}}/api/ops/accounts

###

GET {{ARAS.Auth.Api_HostAddress}}/api/ops/roles

###

@id=ACCcc96453d300a42e29512e6e3a39a18aa9f686912aa2c4e1cbefabc5ec3b9c539
GET {{ARAS.Auth.Api_HostAddress}}/api/ops/accounts/{{id}}

###

GET {{ARAS.Auth.Api_HostAddress}}/api/ops/roles

###

POST {{ARAS.Auth.Api_HostAddress}}/api/ops/accounts
Content-Type: application/json

{
  "id": "ACCf83ecf91f3ad421d887b29ee18f8dd28c5b255cf6c884cacb25c9d6704676e9f",
  "firstName" : "",
  "lastName" : "",
  "accountRole" : "none",
  "groupCode" : "none",
  "isActive" : true
}

###

GET {{ARAS.Auth.Api_HostAddress}}/api/email/approvers

###

GET {{ARAS.Auth.Api_HostAddress}}/api/email/all

###
