@ARAS.Main.Oracle.Api_HostAddress = https://localhost:3004

GET {{ARAS.Main.Oracle.Api_HostAddress}}/weatherforecast/
Accept: application/json

###

@invoiceNo=219395
@count=10
###
GET {{ARAS.Main.Oracle.Api_HostAddress}}/api/invoice/no/219395

###
