@ARAS.Main.Oracle.Api_HostAddress = https://localhost:3004

###

@invoiceNo=500246072
@count=10
###
GET {{ARAS.Main.Oracle.Api_HostAddress}}/api/invoice/no/219395

###

GET {{ARAS.Main.Oracle.Api_HostAddress}}/api/adjustment/reason-codes

###
GET {{ARAS.Main.Oracle.Api_HostAddress}}/api/test/dt

###

GET {{ARAS.Main.Oracle.Api_HostAddress}}/api/adjustment/reason-codes

###