@ARAS.Main.Oracle.Api_HostAddress = https://localhost:3004

###

@invoiceNo=500246072
@count=10
###
GET {{ARAS.Main.Oracle.Api_HostAddress}}/api/invoice/no/219395

###

GET {{ARAS.Main.Oracle.Api_HostAddress}}/api/adjustment/reason-codes

###
GET {{ARAS.Main.Oracle.Api_HostAddress}}/api/test/dt

###

GET {{ARAS.Main.Oracle.Api_HostAddress}}/api/adjustment/reason-codes

###
GET {{ARAS.Main.Oracle.Api_HostAddress}}/api/invoice/one
Content-Type: application/json
{
  "invoiceNumber" : "800022677",
  "invoiceAmount" : 338839.26,
  "invoiceDate" : "2021-05-20",
  "customerName" : "THINKING TOOLS CEBU",
  "customerNumber" : "8044"
}

###

POST {{ARAS.Main.Oracle.Api_HostAddress}}/api/adjustment/stage
Content-Type: application/json

[
    {
      "adjustmentId": 10,
      "invoiceNumber": "197745",
      "adjustmentAmount": 59525,
      "invoiceDate": "2024-10-23T00:00:00",
      "paymentScheduleId": null,
      "dateApplied": "2026-02-03T13:25:07.113",
      "adjustmentActivity": "Cash Discount",
      "reasonCode": "DISCOUNT",
      "remarks": "asdasdasdasda",
      "customerName": "AEROPHONE ENTERPRISES & CO.",
      "customerNumber": "1006"
    }
  ]
###

GET {{ARAS.Main.Oracle.Api_HostAddress}}/api/adjustment/stage

###
